# Generated by Django 4.2.5 on 2023-09-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
