# Generated by Django 4.2.5 on 2023-10-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_quizresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(default='A', max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Single Answer'), ('multi', 'Multi Answer')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
