# Generated by Django 4.2.5 on 2023-10-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_question_answer_question_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
