# Generated by Django 4.2.5 on 2023-10-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_remove_quizresult_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
