# Generated by Django 4.2.5 on 2023-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quizresult_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
