# Generated by Django 4.2.5 on 2023-10-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_question_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='total_questions',
        ),
    ]
