# Generated by Django 4.2.5 on 2023-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_quizresult_total_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='total_question',
            field=models.CharField(max_length=100),
        ),
    ]
